### PR TITLE
Fix detection of "first row, not headline"

### PR DESCRIPTION
**Pull request by mvkorpel**
For me, this fixes the conversion of HTML tables without a header.

### CODE REVIEW

**Comment by AlexVonB** [comment]
Hi! Unfortunately, this breaks some tests. Also, we check for tables without heads and handle them correctly:

https://github.com/matthewwithanm/python-markdownify/blob/b589863715918dca3c8bd3f3ffa0d0b06245bd30/tests/test_tables.py#L124-L140

This is converted to
https://github.com/matthewwithanm/python-markdownify/blob/b589863715918dca3c8bd3f3ffa0d0b06245bd30/tests/test_tables.py#L150

Could you please provide some example? Thanks!

**Comment by AlexVonB** [comment]
Great, thank you! I'll merge this tomorrow to wait for possible last fixes :D Best!

**Comment by mvkorpel** [comment]
Hi @AlexVonB ! My original fix was clearly a sloppy one, as it only addressed a particular case I had: a table with a `<tbody>` but no `<thead>`. Unfortunately, the "fix" broke some other cases which probably were not present in my test input, and I was regrettably too lazy to have run your test suite. The updated pull request should be better. Apologies.

I'm sorry that the commit history now looks a bit dirty.

**Comment by AlexVonB** [comment]
No problem at all! We did not have a test case for just a `tbody`, so your PR is great to improve resiliency! The commits will be squashed on merge, so no worries there. Thanks again!

**Pull request merged**
