### PR TITLE
Fixed issue #52 - added stripping of text to list

### PR DESCRIPTION
**Pull request by Hozhyi**

### CODE REVIEW

**Comment by Hozhyi** [comment]
Fixing issue #52

**Comment by AlexVonB** [comment]
Hi, thanks for the PR! It looks good, please add a test case into https://github.com/matthewwithanm/python-markdownify/blob/develop/tests/test_lists.py so that future code changes don't revert this accidently. Thanks!

**Comment by Hozhyi** [comment]
Hi @AlexVonB, added test case - please review.

**Comment by AlexVonB** [comment]
Perfect! Thank you for your contribution! :) I'll package a new release in the next 10 minutes.

**Pull request merged**
