### PR TITLE
remove prefixed and suffixed spaces from inline tags

### PR DESCRIPTION
**Pull request by AlexVonB**
fixes matthewwithanm#13

Please check if the tests reflect the behavior you want markdownify to have!

### CODE REVIEW

**Comment by SimonIT** [comment]
@matthewwithanm When can I expect to have this PR merged? The issue is really annoying

**Comment by matthewwithanm** [comment]
@SimonIT sorry, I haven't been writing much Python lately and have been a bad maintainer. @AlexVonB any chance you'd be interested in being added as a maintainer and dealing with these pull requests?

**Comment by SimonIT** [comment]
I would also maintain it, if no one volunteers

**Comment by AlexVonB** [comment]
Hey all, sorry, I have been busy. I could maintain, but if Simon volunteers, I am the last to stop him :D

**Comment by matthewwithanm** [comment]
@AlexVonB let's start with you since you have some open PRs (:

i added you to the repo. let me know your pypi account so i can add you to that.

**Comment by AlexVonB** [comment]
Hi, thanks, I am going to work on those PRs and this one. My PyPI account ist AlexVonB. Greetings!

**Comment by matthewwithanm** [comment]
@AlexVonB thanks! ❤️

**Pull request merged**
