### PR TITLE
Support the start attribute for ordered lists

### PR DESCRIPTION
**Pull request by SimonIT**

### CODE REVIEW

**Comment by SimonIT** [comment]
@AlexVonB Can you have a look about this?

**Comment by matthewwithanm** [comment]
Will markdown actually honor restarted lists? In all the dialects I know (including GitHub's), this:

```
1. the
2. quick

6. brown
7. fox
```

will be shown as one list (with the original numbering ignored):

```
1. the
2. quick
3. brown
4. fox
```

It seems a little weird to translate the start attribute to markdown that (when rendered) wouldn't actually preserve it anyway.

In other words, I would expect `markdown(markdownify(html))` to render the same as `html` itself.

**Comment by SimonIT** [comment]
You are right for your example.
But if you have only one list which starts from 6, it does work. Another option ist to put two line breaks between the lists:

```markdown
6. brown
7. fox
```

```markdown
1. the
2. quick


6. brown
7. fox
```
I tried both with https://stackedit.io/

**Comment by AlexVonB** [comment]
6. brown
7. fox

[Indeed](https://www.markdownguide.org/basic-syntax/#lists-1). Should that be included @matthewwithanm ?

**Comment by matthewwithanm** [comment]
that makes sense!

**Pull request merged**
