### PR TITLE
Add methods for code, samp, kbd tags

### PR DESCRIPTION
**Pull request by AndrewCRichards**
Add methods and tests for inline tags `<code>` (also `<samp>` and `<kbd>` using the same base method).

### CODE REVIEW

**Comment by SimonIT** [comment]
Don't you think there will be problems with multiline code, do you?

Just look at your test:
`<code>Line1<br />Line2</code>`  => \`Line1\nLine2\` => `Line1
Line2`

which should be
\`\`\`\nLine1\nLine2\n\`\`\` => 
```
Line1
Line2
```

Or what do you think?

**Comment by AndrewCRichards** [comment]
@SimonIT: Thank you for such a quick response. I don't understand your question, this doesn't seem to match the tests I'm proposing, are you talking about `test_code_with_tricky_content()`?
Please clarify.

**Comment by SimonIT** [comment]
I'm only taking your one test as example.

My problem with the current state is that if you have a multiline html code block (Like your one test) it will converted to one line markdown.
That's what I wanted to show in my last comment

**Comment by AndrewCRichards** [comment]
I think I understand. I believe you're thinking of the `<pre>` tag which I've not tried writing code for in this PR. `<code>` is an in-line tag, so converting <code>Line1<br />Line2</code> to markdown should *not* add leading or trailing newlines.

**Comment by SimonIT** [comment]
That might be true that it's intended to be inline, but with the `<br />` tag it's rendered as multiline if you look here: https://codepen.io/simonit-the-scripter/pen/oNzNGPd

**Comment by AndrewCRichards** [comment]
Yes, that's what's in the test: result is Line1\nLine2, but no leading or trailing \n.

**Comment by AndrewCRichards** [comment]
aha, but now I see why the trailing 2 spaces are needed when converting <br />, otherwise no \n when the markdown is actually rendered. I'll take a look at the test and maybe tidy it up accordingly

**Comment by AndrewCRichards** [comment]
You were absolutely right re. the middle \n, thank you: I had got thrown by your mention of leading and trailing \n. Anyway, now that I understand what the 2 spaces added by the `convert_br()` are doing I've modified the test to expect these, and added a bit of leading and trailing text for good measure, so both the output Markdown and the rendered markdown have a newline where the `<br>` appears.

**Comment by AndrewCRichards** [comment]
Have you had the chance to look at this PR yet?

**Comment by SimonIT** [comment]
I see still a problem with multiple lines:

\`Line1\nLine2\` should display "Line1" in the first line and "Line2" in the second one, but it doesn't. \`\` is only for one line code. From this point we got a dilemma.

1. We can split the code and make convert it to \`Line1\`\n\`Line2\`.  This would work, but can be pretty ugly.:
    `Line1`
    `Line2`
    The pro of it is, that it is still inline. So text can be before and after the lines.

2. The other option is to use \`\`\`\nLine1\nLine2\n\`\`\`. The pro of this method is that it looks good because it's a complete code block. It would also be possible to make code highlighting with this markdown, but I couldn't find a html parameter which has the information for it.
    ```
    Line1
    Line2
    ```
    The con is that it's not possible to have normal text in the same line.

As solution I would would lookup if  in the element `<br/>` elements are present. If not, go with the one line solution \`\` and if yes use \`\`\`\`\`\`.
Or do you see a better solution for this problem?

**Comment by AlexVonB** [comment]
Hi all! Just discovered this PR, my 5 cents: `<code>` may only contain single-line-text: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#notes

>To represent multiple lines of code, wrap the `<code>` element within a `<pre>` element. The `<code>` element by itself only represents a single phrase of code or line of code.

I would resolve the conflicts and merge if there are no objections :)

**Comment by AndrewCRichards** [comment]
Just to say thank you @AlexVonB for picking this up, I think it needed a new pair of eyes to untangle the points raised: Glad to see the PR merged.

**Pull request merged**
